name: video_player_platform_interface
description: A common platform interface for the video_player plugin.
repository: https://github.com/flutter/packages/tree/main/packages/video_player/video_player_platform_interface
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+video_player%22
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 6.4.0
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface:
    git:
      ref: video_player_background_test
      url: https://github.com/ArvidNy/packages.git
      path: packages/plugin_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - video
  - video-player
